simulation:
    Ts:       5       # simulation step size (ms)
    tSample:  1500    # time length of the sample crop (ms) for the simulation
    #tSample:  500    # use this for random crops (train crop length)
    nSample:  8       # number of samples to process at once (batch_size)
neuron:
    type:     SRMALPHA # neuron type
    theta:    10      # neuron threshold
    tauSr:    10.0    # neuron time constant
    tauRef:   10.0    # neuron refractory time constant #1.0
    scaleRef: 20      # neuron refractory response scaling (relative to theta) #2
    tauRho:   1       # spike function derivative time constant (relative to theta)
    scaleRho: 1       # spike function derivative scale factor
training:
    #use the following two lines for fixed crops
    transf_method:    SlayerTD #Transformation method from events to frames
    random_crop:      False    #crop samples to the first 'tSample' ms
                      
    #use the following two lines for random crops                          
    # transf_method:    TonicFrames #Transformation method from events to frames
    # random_crop:      True
    #PS: random_crop only works with TonicFrames, otherwise ignored  
    
    binning_mode:     OR    #SUM #SUM_NORM (how spikes are binned into frames)
                            #PS: SlayerTD has only 'OR' implemented, other choices will be ignored
    sliced_dataset:   True  #False (True is a lighter/faster implementation)
    seed:             0     #control the randomness reproducibility 
    optimizer:        ADAM  #NADAM; SGD
    lr:               0.01  #initial learning rate
    epochs:           3000  #maximum number of training epochs
    CNN:              True  #if True use a spiking CNN, else use a spiking MLP
    error:
        type:         NumSpikes #ProbSpikes #NumSpikes #SpikeTime
        #original parameters: tSample 1500 ms, Region [0-1500], True 180 False 30
        tgtSpikeRegion: {start: 0, stop: 1500}   # only valid for NumSpikes and ProbSpikes
        tgtSpikeCount:  {true: 180, false: 30}   # only valid for NumSpikes
    path:
        out:          output/
        data:         ../data/                                           ## /home/data/
        file_list:    ../data/filelist.txt    #filelist_excludingS3.txt  ## /home/data/filelist.txt
        cache:        ../data/cache/                                     ## /home/data/cache/

#this part below is valid only for random_crop training, otherwise ignored
testing:
    tSample:  4360    # time lenght of the fixed test sample crop (ms)
                      #PS: testing tSsample MUST BE >= simulation tSample
    error:
        tgtSpikeRegion: {start: 0, stop: 4360}  #original [0-1500]
        tgtSpikeCount: {true: 523, false: 87}   #original [True 180, False 30]
                      
        
        
